// Migration 005: MRP procurement demands + inventory movement stream (Modules 5 & 7)

export async function up(client) {
  // Module 5: actionable purchasing requisitions generated by MRP runs
  await client.query(`
    CREATE TABLE IF NOT EXISTS mrp_procurement_demands (
      id SERIAL PRIMARY KEY,
      run_id VARCHAR(40) NOT NULL,
      part_number VARCHAR(100) NOT NULL,
      description VARCHAR(255),
      gross_requirement INTEGER NOT NULL DEFAULT 0,
      on_hand INTEGER NOT NULL DEFAULT 0,
      net_deficiency INTEGER NOT NULL DEFAULT 0,
      suggested_order_qty INTEGER NOT NULL DEFAULT 0,
      estimated_cost NUMERIC(12,2) DEFAULT 0,
      priority VARCHAR(20) DEFAULT 'STANDARD',
      status VARCHAR(20) DEFAULT 'OPEN',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_mrp_demands_run ON mrp_procurement_demands(run_id)`);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_mrp_demands_part ON mrp_procurement_demands(part_number)`);

  // Module 7: real-time inventory movement stream (AP invoice receipts + WO consumption)
  await client.query(`
    CREATE TABLE IF NOT EXISTS inventory_movements (
      id SERIAL PRIMARY KEY,
      part_number VARCHAR(100) NOT NULL,
      change_qty INTEGER NOT NULL,
      source VARCHAR(50) NOT NULL,
      reference VARCHAR(100),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_inventory_movements_part ON inventory_movements(part_number)`);
  await client.query(`CREATE INDEX IF NOT EXISTS idx_inventory_movements_created ON inventory_movements(created_at)`);

  // Note: shop_floor_labor_logs, router_operations, and the open production job seed are
  // owned by migration 008 (restore), keeping this migration order-independent.

  console.log("Migration 005: Created mrp_procurement_demands + inventory_movements, seeded MRP demo demand");
}

export async function down(client) {
  await client.query(`DROP INDEX IF EXISTS idx_inventory_movements_created CASCADE`);
  await client.query(`DROP INDEX IF EXISTS idx_inventory_movements_part CASCADE`);
  await client.query(`DROP TABLE IF EXISTS inventory_movements CASCADE`);
  await client.query(`DROP INDEX IF EXISTS idx_mrp_demands_part CASCADE`);
  await client.query(`DROP INDEX IF EXISTS idx_mrp_demands_run CASCADE`);
  await client.query(`DROP TABLE IF EXISTS mrp_procurement_demands CASCADE`);
  console.log("Migration 005: Rolled back mrp_procurement_demands + inventory_movements");
}
